#include "tokenizer.h"

std::unordered_map<std::string_view, TokenType> Tokenizer::builtinFunctions = {
  {"type",         TokenType::BUILTIN_Type        },
  {"numCast",      TokenType::BUILTIN_NumCast     },
  {"bitCast",      TokenType::BUILTIN_BitCast     },
  {"registerType", TokenType::BUILTIN_RegisterType},
  {"cDefine",      TokenType::BUILTIN_CDefine     },
  {"cUndef",       TokenType::BUILTIN_CUndef      },
  {"cInclude",     TokenType::BUILTIN_CInclude    },
  {"cIncludeDir",  TokenType::BUILTIN_CIncludeDir },
  {"link",         TokenType::BUILTIN_Link        },
  {"linkDir",      TokenType::BUILTIN_LinkDir     },
  {"cImport",      TokenType::BUILTIN_CImport     },
  {"align",        TokenType::BUILTIN_Align       },
  {"local",        TokenType::BUILTIN_Local       },
  {"shared",       TokenType::BUILTIN_Shared      },
  {"global",       TokenType::BUILTIN_Global      },
  {"cudaImport",   TokenType::CudaImport          },
  {"name",         TokenType::BUILTIN_Name        },
  {"cudaPtx",      TokenType::BUILTIN_CudaPtx     },
  {"blockIdxX",    TokenType::CudaBlockIdxX       },
  {"blockIdxY",    TokenType::CudaBlockIdxY       },
  {"blockIdxZ",    TokenType::CudaBlockIdxZ       },
  {"blockDimX",    TokenType::CudaBlockDimX       },
  {"blockDimY",    TokenType::CudaBlockDimY       },
  {"blockDimZ",    TokenType::CudaBlockDimZ       },
  {"threadIdxX",   TokenType::CudaThreadIdxX      },
  {"threadIdxY",   TokenType::CudaThreadIdxY      },
  {"threadIdxZ",   TokenType::CudaThreadIdxZ      },
  {"gridDimX",     TokenType::CudaGridDimX        },
  {"gridDimY",     TokenType::CudaGridDimY        },
  {"gridDimZ",     TokenType::CudaGridDimZ        },
  {"crash",        TokenType::BUILTIN_Crash       },
  {"sizeOf",       TokenType::BUILTIN_Sizeof      },
  {"alignOf",      TokenType::BUILTIN_Alignof     },
  {"bitSize",      TokenType::BUILTIN_Bitsize     },
  {"ptrCast",      TokenType::BUILTIN_PtrCast     },
  {"bInclude",     TokenType::BUILTIN_Binclude    },
  {"raw",          TokenType::BUILTIN_Raw         },
};

std::unordered_map<std::string_view, TokenType> Tokenizer::keywords = {
  {"fn",        TokenType::Function },
  {"kernel",    TokenType::Kernel   },
  {"struct",    TokenType::Struct   },
  {"if",        TokenType::If       },
  {"else",      TokenType::Else     },
  {"true",      TokenType::True     },
  {"false",     TokenType::False    },
  {"and",       TokenType::LogicAnd },
  {"or",        TokenType::LogicOr  },
  {"for",       TokenType::For      },
  {"while",     TokenType::While    },
  {"import",    TokenType::Import   },
  {"union",     TokenType::Union    },
  {"enum",      TokenType::Enum     },
  {"trait",     TokenType::Trait    },
  {"impl",      TokenType::Impl     },
  {"mut",       TokenType::Mut      },
  {"opaque",    TokenType::Opaque   },
  {"gn",        TokenType::Generic  },
  {"return",    TokenType::Return   },
  {"Self",      TokenType::Self     },
  {"using",     TokenType::Using    },
  {"when",      TokenType::When     },
  {"test",      TokenType::Test     },
  {"invariant", TokenType::Invariant},
  {"null",      TokenType::Null     },
};
